window.LANGUAGES = window.LANGUAGES || {};

window.LANGUAGES.en = {
  "nativeName": "English",
  "translations": {
    "عامة": "General",
    "ألبان وأجبان": "Dairy & Cheese",
    "معلبات": "Canned Goods",
    "مشروبات وعصائر": "Beverages & Juices",
    "لحوم ودواجن": "Meat & Poultry",
    "خضار وفواكه": "Vegetables & Fruits",
    "مخبوزات وحلويات": "Bakery & Sweets",
    "بهارات وعطارة": "Spices & Herbs",
    "منظفات": "Cleaning Supplies",
    "عناية شخصية": "Personal Care",
    "مستلزمات أطفال": "Baby Supplies",
    "وجبات خفيفة وشيبس": "Snacks & Chips",
    "أدوات منزلية": "Household Items",
    "قرطاسية": "Stationery",
    "smart_pos_system": "Smart POS System",
    "welcome_back": "Welcome back to the Smart Management System",
    "dashboard": "Dashboard",
    "cashier": "Cashier",
    "products": "Products",
    "inventory": "Inventory",
    "purchases": "Companies & Purchases",
    "sales": "Sales History",
    "customers": "Customers",
    "suppliers": "Suppliers",
    "debts": "Customer Debts",
    "accounts": "Accounts",
    "reports": "Reports",
    "employees": "Employees",
    "discounts": "Offers & BOGO",
    "barcode": "Print Barcode",
    "settings": "Settings",
    "main_menu": "Main Menu",
    "finance_reports": "Finance & Reports",
    "tools_settings": "Tools & Settings",
    "connected": "Online",
    "products_inv": "Products & Inventory",
    "finance_rep": "Finance & Reports",
    "offers_disc": "Offers & Discounts",
    "settings_sys": "Settings & System",
    "alerts": "Alerts",
    "active_system": "System is connected & active",
    "logout_btn": "Logout",
    "exchange_rate": "Current USD Rate",
    "iqd_currency": "IQD",
    "pos_desc": "Fast checkout interface and invoicing system",
    "products_desc": "Product catalog, stock levels, barcodes & labels",
    "debts_desc": "Customer directory, customer debts, and payment logs",
    "purchases_desc": "Purchase bills, suppliers, returns & payments",
    "reports_desc": "Dashboard, sales & expenses, archive & logs",
    "discounts_desc": "Discounts, sale coupons, and membership offers",
    "settings_desc": "Store & currency details, printer settings, backup & alerts",
    "alerts_desc": "Inventory, debts & transaction notifications",
    "lang_changed_success": "Language changed successfully",
    "home": "Home",
    "shopping_cart": "Shopping Cart",
    "guest_customer": "-- Guest Customer (Search) --",
    "tax_label": "Tax",
    "coupon_code": "Coupon Code",
    "الكل": "All",
    "مواد بالوزن": "Weighted Items",
    "قطعة": "Piece",
    "علبة": "Box",
    "كيس": "Bag",
    "كيلو": "kg",
    "غرام": "g",
    "لتر": "L",
    "متر": "m",
    "مواد غذائية": "Groceries",
    "مشروبات": "Drinks",
    "منتجات الألبان": "Dairy",
    "خضار وفواكه": "Fruits & Veggies",
    "لحوم ودواجن": "Meat & Poultry",
    "لحوم": "Meat",
    "منظفات": "Detergents",
    "حلويات": "Sweets",
    "معلبات": "Canned Food",
    "خبز عيش": "Bread",
    "حليب كامل الدسم": "Whole Milk",
    "عصير برتقال": "Orange Juice",
    "تفاح أحمر": "Red Apple",
    "دجاج مجمد": "Frozen Chicken",
    "شوكولاتة كيت كات": "KitKat",
    "سبراي تنظيف": "Cleaning Spray",
    "فاصولياء معلبة": "Canned Beans",
    "مياه معدنية": "Mineral Water",
    "زيت نباتي": "Vegetable Oil",
    "سكر أبيض": "White Sugar",
    "أرز بسمتي": "Basmati Rice",
    "هل تريد تسجيل الخروج؟": "Are you sure you want to logout?",
    "المنتج غير موجود بهذا الباركود": "Product not found with this barcode",
    "تمت عملية البيع بنجاح": "Sale completed successfully",
    "تم حفظ الفاتورة كدين": "Invoice saved as debt",
    "تم استبدال النقاط بنجاح": "Points redeemed successfully",
    "هل تريد إفراغ السلة؟": "Are you sure you want to clear the cart?",
    "هل أنت متأكد من حذف هذا المنتج؟": "Are you sure you want to delete this product?",
    "يرجى تحديد المبلغ المدفوع بشكل صحيح": "Please specify the paid amount correctly",
    "إجمالي الأصناف المباعة": "Total Sold Categories",
    "إعدادات الطابعة": "Printer Settings",
    "منتجات ناقصة": "Out of Stock Products",
    "اشترِ واحداً واحصل على آخر": "Buy One Get One",
    "🔑 تسجيل الدخول": "🔑 Login",
    "مبيعات اليوم": "Today's Sales",
    "طباعة صفحة اختبار": "Print Test Page",
    "عدد نسخ الفاتورة": "Number of Invoice Copies",
    "التكلفة الكلية": "Total Cost",
    "القيمة": "Value",
    "طابعة شبكية": "Network Printer",
    "📅 يومي": "📅 Daily",
    "التفاصيل": "Details",
    "مواد مباعة": "Sold Items",
    "الاستخدامات": "Uses",
    "المنتج الخاضع للعرض": "Offer Product",
    "إدارة المخزون": "Inventory Manage",
    "إدارة العملاء": "Customers Manage",
    "ديون العملاء": "Customer Debts",
    "التقارير": "Reports",
    "الإعدادات": "Settings",
    "الأرشيف": "Archive",
    "لوحة التحكم": "Dashboard",
    "المشتريات": "Purchases",
    "المبيعات": "Sales",
    "الموردون": "Suppliers",
    "الحسابات": "Accounts",
    "الموظفون": "Employees",
    "العروض والخصومات": "Offers & Discounts",
    "الباركود": "Barcode",
    "📷 إدارة الباركود": "📷 Barcode Management",
    "⬇️ تحميل الباركود": "⬇️ Download Barcode",
    "🏷️ إعدادات ملصقات الأسعار": "🏷️ Price Labels Settings",
    "📋 دليل المعاينة والتعليمات": "📋 Preview Guide & Instructions",
    "ℹ️ مواصفات القالب المختار:": "ℹ️ Selected Template Specs:",
    "📹 تشغيل كاميرا الجهاز للمسح": "📹 Turn on device camera for scanning",
    "إعدادات الطباعة": "Printer Settings",
    "الإشعارات": "Notifications",
    "النسخ الاحتياطي": "Backup",
    "سجل العمليات": "Activity Log",
    "تسجيل الخروج": "Logout",
    "المنتجات": "Products",
    "معاً": "Both",
    "السلة": "Cart",
    "سلة المشتريات": "Shopping Cart",
    "مسح": "Clear",
    "المجموع الفرعي:": "Subtotal:",
    "الخصم": "Discount",
    "الضريبة": "Tax",
    "الإجمالي:": "Total:",
    "نقداً": "Cash",
    "بطاقة": "Card",
    "تحويل": "Transfer",
    "دين": "Debt",
    "دينار عراقي": "Iraqi Dinar",
    "دولار أمريكي": "US Dollar",
    "المبلغ المدفوع (د.ع):": "Paid Amount (IQD):",
    "دفع صافي": "Exact Amount",
    "الباقي:": "Change:",
    "الدفع بالبطاقة الائتمانية": "Credit Card Payment",
    "سيتم خصم المبلغ تلقائياً عبر الجهاز": "Amount will be automatically charged via terminal",
    "الدفع بالتحويل الإلكتروني": "Electronic Transfer Payment",
    "تأكد من استلام التحويل قبل إتمام البيع": "Confirm receipt of transfer before completing sale",
    "رقم التحويل / ملاحظة (اختياري)": "Transfer Ref / Note (Optional)",
    "بيع بالدين": "Sell on Debt",
    "يجب اختيار عميل من القائمة أعلاه": "Must select a customer from the list above",
    "ملاحظة الدين (اختياري)": "Debt Note (Optional)",
    "إتمام البيع": "Complete Sale",
    "تأكيد الإجراء": "Confirm Action",
    "نعم، إتمام الإجراء": "Yes, proceed",
    "نعم، خروج": "Yes, exit",
    "موافق": "OK",
    "تعديل المنتج": "Edit Product",
    "أدخل الباركود": "Enter Barcode",
    "توليد": "Generate",
    "مسح_كاميرا": "Scan",
    "اختر الفئة": "Select Category",
    "الوحدة": "Unit",
    "حزمة": "Bundle",
    "كرتون": "Carton",
    "سعر البيع (د.ع)": "Selling Price (IQD)",
    "سعر البيع ($)": "Selling Price ($)",
    "سعر الشراء (د.ع)": "Purchase Price (IQD)",
    "الحد الأدنى للمخزون": "Minimum Stock",
    "صورة / رمز تعبيري": "Image / Emoji",
    "تاريخ الصلاحية (اختياري)": "Expiry Date (Optional)",
    "ملاحظات": "Notes",
    "ملاحظات إضافية": "Additional Notes",
    "حفظ المنتج": "Save Product",
    "اختر إيموجي": "Select Emoji",
    "رفع صورة": "Upload Image",
    "طبيعي": "Normal",
    "تحويل مخزوني": "Transfer Stock",
    "+ إضافة مخزون": "+ Add Stock",
    "المبيعات والكاشير": "Sales & Cashier",
    "إدارة المتجر": "Store Management",
    "النظام والإدارة": "System & Admin",
    "لوحة الإدارة": "Admin Dashboard",
    "تنزيل على سطح المكتب": "Download App",
    "متصل": "Connected",
    "الحد الأدنى": "Minimum",
    "إضافة كمية": "Add Quantity",
    "السعر (د.ع)": "Price (IQD)",
    "السعر ($)": "Price ($)",
    "إجمالي المنتجات": "Total Products",
    "نفد المخزون": "Out of Stock",
    "إدارة الباركود": "Barcode Management",
    "إنشاء باركود": "Generate Barcode",
    "طباعة الملصقات": "Print Labels",
    "قارئ الباركود": "Barcode Reader",
    "إعدادات الباركود": "Barcode Settings",
    "معاينة ملصق الباركود": "Barcode Label Preview",
    "اختر منتجاً أو أدخل رقماً لعرض الباركود": "Select a product or enter a number to display barcode",
    "طباعة الملصق": "Print Label",
    "إعدادات ملصقات الأسعار": "Price Labels Settings",
    "عدد الملصقات": "Number of Labels",
    "حجم الملصق": "Label Size",
    "صغير (58mm)": "Small (58mm)",
    "متوسط (80mm)": "Medium (80mm)",
    "كبير (A4)": "Large (A4)",
    "دليل المعاينة والتعليمات": "Preview Guide & Instructions",
    "مواصفات القالب المختار:": "Selected Template Specs:",
    "قالب 58mm:": "58mm Template:",
    "قالب طباعة حراري أحادي العمود، مثالي لطابعات الفواتير الصغيرة أو طابعات الموازين الإلكترونية.": "Single column thermal print template, ideal for small receipt printers or electronic scale printers.",
    "قالب 80mm:": "80mm Template:",
    "قالب طباعة حراري ثنائي الأعمدة، مناسب لطابعات الباركود المخصصة للمحلات التجارية الكبيرة.": "Two column thermal print template, suitable for barcode printers dedicated to large commercial stores.",
    "قالب A4:": "A4 Template:",
    "ورقة طباعة مكتبية قياسية، تحتوي على شبكة من 24 ملصقاً (3 أعمدة × 8 صفوف)، مناسبة للطابعات المكتبية العادية.": "Standard office print sheet, containing a grid of 24 labels (3 columns x 8 rows), suitable for regular office printers.",
    "تأكد من اختيار مقاس الورق الصحيح (Paper Size) في نافذة خيارات الطباعة للمتصفح لتجنب انحراف الباركود.": "Ensure selecting the correct paper size in the browser print options window to avoid barcode misalignment.",
    "قارئ الباركود الذكي": "Smart Barcode Reader",
    "تشغيل كاميرا الجهاز للمسح": "Turn on device camera for scanning",
    "مثال: 628123456789": "E.g., 628123456789",
    "امسح الباركود هنا...": "Scan barcode here...",
    "امسح الباركود باستخدام قارئ خارجي أو كاميرا الجهاز مباشرة": "Scan barcode using external scanner or device camera directly",
    "حاسبة الأكياس / الجملة (اختياري)": "Bag / Wholesale Calculator (Optional)",
    "* سيتم حساب سعر الكيلو الإفرادي والمخزون الكلي (بالكيلو) تلقائياً بالأسفل.": "* Unit price and total stock (in kg) will be calculated automatically below.",
    "وزن الكيس (كيلو)": "Bag Weight (kg)",
    "عدد الأكياس المشتراة": "Number of Bags Purchased",
    "سعر شراء الكيس": "Bag Purchase Price",
    "سعر بيع الكيس كاملاً": "Full Bag Selling Price",
    "مثال: 5": "E.g., 5",
    "مثال: 10": "E.g., 10",
    "مثال: 25000": "E.g., 25000",
    "مثال: 28000": "E.g., 28000",
    "استرجاع": "Refund/Return",
    "اضغط \"إتمام البيع\" بعد تأكيد الدفع على الجهاز": "Press \"Complete Sale\" after confirming payment on the terminal",
    "اضغط \"إتمام البيع\" بعد التأكد من وصول التحويل": "Press \"Complete Sale\" after confirming transfer receipt",
    "تسجيل بالدين": "Save as Debt",
    "السلة فارغة": "Cart is empty",
    "أضف منتجات من القائمة": "Add products from the list",
    "استبدال النقاط": "Redeem Points",
    "🔍 ابحث بالاسم أو الباركود...": "🔍 Search by name or barcode...",
    "📷 كاميرا": "📷 Camera",
    "⌨️ محاكاة": "⌨️ Simulate",
    "الفرع الرئيسي": "Main Branch",
    "المستودع الرئيسي": "Main Warehouse",
    "إضافة منتج جديد": "Add New Product",
    "اسم المنتج": "Product Name",
    "سعر الشراء (التكلفة)": "Cost Price",
    "سعر البيع": "Selling Price",
    "الكمية في المخزون": "Quantity in Stock",
    "حفظ": "Save",
    "تعديل": "Edit",
    "حذف": "Delete",
    "الرقم": "ID",
    "الاسم": "Name",
    "سعر التكلفة": "Cost",
    "السعر": "Price",
    "المخزون": "Stock",
    "العمليات": "Actions",
    "البيانات الأساسية": "Basic Info",
    "اسم المتجر": "Store Name",
    "العنوان": "Address",
    "رقم الهاتف": "Phone Number",
    "إعدادات العملة": "Currency Settings",
    "سعر صرف الدولار (د.ع)": "USD Exchange Rate (IQD)",
    "العملة الافتراضية": "Default Currency",
    "إعدادات الفواتير": "Invoice Settings",
    "نسبة الضريبة (%)": "Tax Rate (%)",
    "تنبيه الحد الأدنى للمخزون": "Min Stock Alert Level",
    "ملاحظة أسفل الفاتورة": "Invoice Footer Note",
    "حفظ الإعدادات": "Save Settings",
    "إعادة ضبط البيانات": "Reset All Data",
    "حساب التلغرام لإرسال الفواتير": "Telegram Account for Invoices",
    "كود الكوبون": "Coupon Code",
    "-- عميل زائر (بحث) --": "-- Guest Customer (Search) --",
    "تسديد ديون عميل": "Pay Customer Debt",
    "دليل العملاء": "Customer Directory",
    "إجمالي الديون": "Total Debts",
    "عدد المدينين": "Number of Debtors",
    "عدد عمليات الدين": "Number of Debt Operations",
    "إجمالي المسدد": "Total Paid",
    "العملاء المدينون": "Debtor Customers",
    "اختر عميلاً لعرض تفاصيل ديونه": "Select a customer to view debt details",
    "عملية": "operation",
    "الديون الجديدة (فواتير النظام)": "New Debts (System Invoices)",
    "إجمالي المتبقي الجديد": "Total New Remaining",
    "مسدد من الجديد": "Paid from New",
    "إجمالي الفواتير": "Total Invoices",
    "تسديد دفعة من الديون الجديدة": "Pay Installment from New Debts",
    "المتبقي": "Remaining",
    "متبقي": "Remaining",
    "لا توجد فواتير ديون جديدة": "No new debt invoices",
    "غير مسدد": "Unpaid",
    "مسدد جزئياً": "Partially Paid",
    "مسدد بالكامل": "Fully Paid",
    "كاشير": "Cashier",
    "المنتجات المشتراة": "Purchased Products",
    "إجمالي الفاتورة": "Invoice Total",
    "سجل الدفعات": "Payments History",
    "تسجيل دفعة": "Register Payment",
    "تم السداد الكامل": "Fully Paid",
    "سجل الديون السابقة (القديمة)": "Previous Debts Record (Old)",
    "إجمالي الدين القديم": "Total Old Debt",
    "ما تم تسديده": "Amount Paid",
    "المتبقي من القديم": "Remaining from Old",
    "تسديد من الدين القديم": "Pay from Old Debt",
    "تم تسديد الدين القديم بالكامل": "Old Debt Fully Paid",
    "+ فاتورة شراء جديدة": "+ New Purchase Invoice",
    "فواتير الشراء": "Purchase Invoices",
    "المرتجعات": "Returns",
    "الدفعات": "Payments",
    "المورد": "Supplier",
    "التاريخ": "Date",
    "الإجمالي": "Total",
    "لا توجد فواتير شراء بعد": "No purchase invoices yet",
    "+ إضافة مورد": "+ Add Supplier",
    "اسم المورد": "Supplier Name",
    "الهاتف": "Phone",
    "الشركة": "Company",
    "الدين": "Debt",
    "لا يوجد موردون بعد": "No suppliers yet",
    "المبلغ": "Amount",
    "السبب": "Reason",
    "لا توجد مرتجعات بعد": "No returns yet",
    "الملاحظة": "Note",
    "لا توجد دفعات بعد": "No payments yet",
    "لا توجد دفعات مسجلة بعد": "No recorded payments yet",
    "لا توجد إشعارات تستحق الانتباه حالياً": "No notifications require attention currently",
    "سجل السلال": "Carts Log",
    "المنتجات المباعة": "Sold Products",
    "Kurdî Soranî": "Kurdî Soranî",
    "لا توجد سلال في هذه الفترة": "No carts in this period",
    "فواتير اليوم": "Today's Invoices",
    "📥 تحميل نسخة احتياطية (JSON)": "📥 Download Backup (JSON)",
    "🏆 أكثر الأصناف مبيعاً": "🏆 Top Selling Categories",
    "آخر الفواتير": "Latest Invoices",
    "📋 سجل العمليات": "📋 Activity Log",
    "شهرياً": "Monthly",
    "+ إضافة خصم": "+ Add Discount",
    "لا توجد سلال مؤرشفة": "No archived carts",
    "🔔 الإشعارات والتنبيهات": "🔔 Notifications & Alerts",
    "🏦 الحسابات": "🏦 Accounts",
    "💳 طرق الدفع": "💳 Payment Methods",
    "Kurdî Badînî": "Kurdî Badînî",
    "كلمة المرور الجديدة": "New Password",
    "متوسط قيمة الفاتورة": "Average Invoice Value",
    "نقص مخزون": "Low Stock",
    "📅 صلاحية": "📅 Validity",
    "🗂️ الأرشيف": "🗂️ Archive",
    "📤 استعادة البيانات": "📤 Restore Data",
    "0 د.ع": "0 IQD",
    "إلى": "To",
    "رقم الفاتورة": "Invoice Number",
    "إنشاء نسخة احتياطية": "Create Backup",
    "إعدادات إشعارات التليجرام": "Telegram Notification Settings",
    "الإيراد": "Revenue",
    "تاريخ التفعيل": "Activation Date",
    "النسخ الاحتياطي والاستعادة": "Backup & Restore",
    "📦 المشتريات وإضافة المخزون": "📦 Purchases & Stock Additions",
    "💰 المبيعات": "💰 Sales",
    "⚠️ مخزون": "⚠️ Stock",
    "التقارير والمبيعات": "Reports & Sales",
    "اللغة": "Language",
    "انتهاء صلاحية": "Expiration",
    "تحديث": "Update",
    "💵 تسديدات": "💵 Payments",
    "+ إضافة عرض BOGO": "+ Add BOGO Offer",
    "تسديدات مستلمة": "Received Payments",
    "عدد الفواتير": "Number of Invoices",
    "🏆 أكثر المنتجات مبيعاً اليوم": "🏆 Top Selling Products Today",
    "طباعة المتصفح (افتراضي)": "Browser Print (Default)",
    "ديون مستحقة": "Due Debts",
    "متوسط الفاتورة": "Average Invoice",
    "الحد الأدنى للمخزون (تنبيه)": "Minimum Stock Level (Alert)",
    "🔔 الكل": "🔔 All",
    "طابعة حرارية USB/Bluetooth": "Thermal Printer USB/Bluetooth",
    "âš™️ معلومات المتجر": "⚙️ Store Information",
    "عدد السلال المكتملة": "Number of Completed Carts",
    "📋 جميع العمليات": "📋 All Activities",
    "الكمية المضافة": "Added Quantity",
    "قريب الانتهاء": "Nearing Expiration",
    "تاريخ الانتهاء": "Expiration Date",
    "🔴 غير مقروءة": "🔴 Unread",
    "نوع الطابعة": "Printer Type",
    "أرباح اليوم": "Today's Profits",
    "📥 طباعة": "📥 Print",
    "معرف التليجرام (Username)": "Telegram Username",
    "🗑️ مسح جميع البيانات": "🗑️ Clear All Data",
    "🎟️ كوبونات الخصم": "🎟️ Discount Coupons",
    "إجمالي الأرباح": "Total Profits",
    "فاتورة حرارية": "Thermal Invoice",
    "âš™️ إعدادات المتجر": "⚙️ Store Settings",
    "الربح": "Profit",
    "58 ملم (صغير)": "58 mm (Small)",
    "حجم الورق": "Paper Size",
    "اختر ملف النسخة الاحتياطية": "Select Backup File",
    "نوع العملية": "Activity Type",
    "دينار عراقي (د.ع)": "Iraqi Dinar (IQD)",
    "تأكيد كلمة المرور": "Confirm Password",
    "العميل": "Customer",
    "+ إضافة كوبون": "+ Add Coupon",
    "أكثر المنتجات مبيعاً": "Top Selling Products",
    "كل شيء على ما يرام!": "Everything is fine!",
    "حفظ إعدادات الطباعة": "Save Print Settings",
    "النسخ الاحتياطي التلقائي": "Automatic Backup",
    "التاريخ والوقت": "Date & Time",
    "أسبوعياً": "Weekly",
    "يومياً": "Daily",
    "نوع الخصم": "Discount Type",
    "متوسط السلة": "Average Cart",
    "خصومات المنتجات": "Product Discounts",
    "80 ملم (متوسط)": "80 mm (Medium)",
    "تكرار النسخ الاحتياطي": "Backup Frequency",
    "العربية": "العربية",
    "إجمالي المبيعات": "Total Sales",
    "اختبار الطباعة": "Test Print",
    "دولار أمريكي ($)": "US Dollar ($)",
    "💳 ديون": "💳 Debts",
    "📦 المنتجات": "📦 Products",
    "إعدادات المستخدم": "User Settings",
    "مبلغ ثابت": "Fixed Amount",
    "البطاقات": "Cards",
    "سجل دين": "Debt Record",
    "المتبقي بعد السداد": "Remaining after payment",
    "منتج غير معروف": "Unknown Product",
    "اسم العميل": "Customer Name",
    "تاريخ النسخة": "Version Date",
    "كل 6 ساعات": "Every 6 hours",
    "اقترب من النفاذ": "Nearing Empty",
    "طباعة ملصقات الأسعار": "Print Price Labels",
    "انتهت في": "Ended at",
    "تقرير دوري تلقائي": "Automatic Periodic Report",
    "تحديث دوري": "Periodic Update",
    "إجمالي العرض": "Total Offer",
    "تم سداد": "Paid",
    "البنك": "Bank",
    "انتهت صلاحية": "Expired",
    "الصندوق": "Cashbox",
    "العملاء المدينين": "Indebted Customers",
    "نقاط الولاء المتاحة": "Available Loyalty Points",
    "الكمية المسترجعة": "Returned Quantity",
    "لا توجد مبيعات اليوم": "No Sales Today",
    "عميل غير محدد": "Unspecified Customer",
    "موظف الكاشير": "Cashier Employee",
    "صندوق النقدية": "Cash Drawer",
    "للإدارة": "For Management",
    "لا توجد منتجات": "No Products",
    "إضافة لمخزون مادة": "Add to Item Stock",
    "كشف حسابات العملاء": "Customer Accounts Statement",
    "لا توجد خصومات على المنتجات": "No Product Discounts",
    "لا توجد مرتجعات موردين بعد": "No Supplier Returns Yet",
    "تقرير المبيعات": "Sales Report",
    "تم التسليم": "Delivered",
    "إيداع نقدي": "Cash Deposit",
    "عملية بيع جديدة": "New Sale Transaction",
    "نسبة مئوية": "Percentage",
    "تسجيل مصروف": "Record Expense",
    "لا توجد عروض": "No Offers",
    "تنبيهات المخزون": "Stock Alerts",
    "إجمالي العملاء المسجلين": "Total Registered Customers",
    "تسديد حساب للمورد": "Payment to supplier",
    "تحويل مخزوني للمنتج": "Product Stock Transfer",
    "لا توجد كميات متاحة": "No Quantities Available",
    "التحويلات": "Transfers",
    "لا توجد نتائج": "No Results",
    "سيتم سداد ديون العميل بالكامل": "Customer's debt will be fully paid",
    "تسديد حساب من": "Payment from",
    "غير محدد": "Unspecified",
    "تقرير شامل بأسماء العملاء والأرصدة المستحقة": "Comprehensive report with customer names and due balances",
    "عملية استرجاع مواد": "Items Return Process",
    "المخزون الحالي": "Current Stock",
    "الرصيد المستحق": "Due Balance",
    "المبلغ أكبر من الدين القديم المتبقي": "Amount is greater than remaining old debt",
    "لا توجد مبيعات في هذه الفترة": "No sales in this period",
    "دفعة فاتورة شراء للمورد": "Purchase Invoice Payment to Supplier",
    "صافي الأرباح": "Net Profits",
    "شراء بضاعة": "Purchase Goods",
    "آخر نسخة احتياطية": "Last Backup",
    "تحويل لبيع": "Convert to Sale",
    "تم استرجاع المواد بنجاح": "Items returned successfully",
    "تعليم كمقروء": "Mark as Read",
    "الأزرار": "Buttons",
    "عملية بيع بالدين": "Debt Sale Transaction",
    "هذه صفحة اختبار للطباعة": "This is a test print page",
    "عميل عام": "General Customer",
    "بلا حد": "Unlimited",
    "لا توجد حجوزات مسجلة بعد": "No Reservations Logged Yet",
    "لا توجد كوبونات": "No Coupons",
    "تقرير مبيعات المحل": "Store Sales Report",
    "نفد مخزون": "Out of Stock",
    "تسديد دفعة ديون": "Pay Debt Installment",
    "تاريخ الطباعة": "Print Date",
    "تم تسجيل دفعة": "Payment Recorded",
    "إضافة مادة جديدة": "Add New Item",
    "عرض سعر رسمي": "Official Quotation",
    "مقدم إلى": "Presented To",
    "طريقة الدفع": "Payment Method",
    "صافي الصندوق نقداً": "Net Cashbox",
    "فاتورة شراء منتج": "Product Purchase Invoice",
    "المبلغ المسدد": "Paid Amount",
    "لا توجد مصروفات مسجلة": "No recorded expenses",
    "الكمية الحالية": "Current Quantity",
    "حذف العرض": "Delete Offer",
    "لا توجد عروض أسعار مسجلة بعد": "No Quotations Logged Yet",
    "لا توجد تنبيهات": "No Alerts",
    "لا توجد ديون مسجلة": "No Recorded Debts",
    "منتهي": "Ended / Expired",
    "الرجاء إدخال مبلغ صحيح": "Please enter a valid amount",
    "إجمالي الديون المستحقة": "Total Due Debts",
    "سيتم سداد الدين بالكامل": "Debt will be fully paid",
    "لا يوجد عملاء": "No Customers",
    "لا توجد قيود يومية مسجلة بعد": "No journal entries recorded yet",
    "تم تسجيل دين على": "Debt recorded on",
    "تسديد دين قديم": "Pay Old Debt",
    "بدون رقم": "No Number",
    "إثبات فاتورة مبيعات": "Sales Invoice Proof",
    "المبلغ المتبقي": "Remaining Amount",
    "مجمل الربح": "Gross Profit",
    "المصروفات التشغيلية والرواتب": "Operating Expenses & Salaries",
    "سحب نقدي": "Cash Withdrawal",
    "بند المصروف": "Expense Item",
    "المبلغ (د.ع)": "Amount (IQD)",
    "الحساب الدائن": "Credit Account",
    "الصندوق (نقداً)": "Safe (Cash)",
    "البنك (تحويل/بطاقة)": "Bank (Transfer/Card)",
    "ملاحظة": "Note",
    "مثال: فاتورة كهرباء، إيجار": "Example: Electricity bill, Rent",
    "ملاحظة إضافية": "Additional note",
    "حفظ المصروف": "Save Expense",
    "إلغاء": "Cancel",
    "المصدر": "Source",
    "البند": "Item",
    "البيان": "Description",
    "مدين": "Debit",
    "دائن": "Credit",
    "الرصيد": "Balance",
    "الفترة": "Period",
    "صندوق النقدية (الكاش)": "Cashbox (Cash)",
    "حساب البنك (التحويلات/البطاقات)": "Bank Account (Transfers/Cards)",
    "مبيعات - فاتورة #": "Sales - Invoice #",
    "بطاقة/تحويل": "Card/Transfer",
    "إجمالي الإيرادات (المبيعات)": "Total Revenues (Sales)",
    "تكلفة البضاعة المباعة (COGS)": "Cost of Goods Sold (COGS)",
    "مجمل الربح (Gross Profit)": "Gross Profit",
    "صافي الأرباح (Net Profit)": "Net Profit",
    "إثبات فاتورة مبيعات #": "Record Sales Invoice #",
    "إثبات تكلفة البضاعة المباعة لفاتورة #": "Record COGS for Invoice #",
    "شراء بضاعة:": "Purchase of goods:",
    "من المورد": "from supplier",
    "تسجيل مصروف:": "Record expense:",
    "الحساب البنكي": "Bank Account",
    "إيرادات المبيعات": "Sales Revenues",
    "تكلفة البضاعة المباعة": "Cost of Goods Sold",
    "مخزون المنتجات": "Products Inventory",
    "حساب المورد الدائن": "Supplier Credit Account",
    "مصاريف تشغيلية": "Operating Expenses",
    "إضافة عرض/خصم جديد": "Add New Offer/Discount",
    "المنتج المستهدف": "Target Product",
    "نوع العرض": "Offer Type",
    "خصم نسبة مئوية (%)": "Percentage Discount (%)",
    "خصم مبلغ ثابت (د.ع)": "Fixed Amount Discount (IQD)",
    "اشتري 1 واحصل على 1 مجاناً (BOGO)": "Buy 1 Get 1 Free (BOGO)",
    "قيمة الخصم": "Discount Value",
    "حفظ العرض": "Save Offer",
    "إضافة كوبون خصم جديد": "Add New Discount Coupon",
    "رمز الكوبون (كود)": "Coupon Code",
    "نسبة مئوية (%)": "Percentage (%)",
    "مبلغ ثابت (د.ع)": "Fixed Amount (IQD)",
    "الحد الأقصى للاستخدام": "Max Usage Limit",
    "غير محدود": "Unlimited",
    "إضافة الكوبون": "Add Coupon",
    "مثال: SAVE20": "Example: SAVE20",
    "قم بحفظ نسخة احتياطية كاملة من بيانات النظام (المنتجات، الفواتير، العملاء، الإعدادات)": "Save a full backup of system data (Products, Invoices, Customers, Settings)",
    "تصدير إلى Excel (CSV)": "Export to Excel (CSV)",
    "تحذير: استعادة البيانات ستحل محل جميع البيانات الحالية": "Warning: Restoring data will overwrite all current data",
    "تفعيل النسخ الاحتياطي التلقائي": "Enable Automatic Backup",
    "آخر نسخة احتياطية: لم يتم إنشاء نسخة بعد": "Last backup: No backup created yet",
    "آخر نسخة احتياطية:": "Last backup:",
    "لا توجد إيرادات": "No Revenues",
    "إجمالي الإيرادات": "Total Revenues",
    "لا توجد سجلات عمليات": "No Activity Logs",
    "مخزون منخفض": "Low Stock",
    "تعليم الكل كمقروء": "Mark all as read",
    "إجمالي": "Total",
    "إظهار الشعار": "Show Logo",
    "طباعة الباركود على الفاتورة": "Print Barcode on Invoice",
    "طباعة تلقائية بعد البيع": "Auto Print After Sale",
    "telegram_activation": "To activate service: Send a message to <code>@CallMeBot_API</code> bot on Telegram and press Start.",
    "تسديد ديون قديمة": "Pay Old Debts",
    "نظام الكاشير": "POS System",
    "سوبر ماركيت": "Supermarket",
    "اسم المستخدم": "Username",
    "أدخل اسم المستخدم": "Enter Username",
    "كلمة المرور": "Password",
    "أدخل كلمة المرور": "Enter Password",
    "دخول": "Login",
    "المستخدم: admin | كلمة المرور: 1234": "User: admin | Password: 1234",
    "إعادة طباعة": "Reprint",
    "استرجاع منتجات": "Return Products",
    "إجمالي عرض السعر": "Total Quotation",
    "لا توجد بيانات": "No Data",
    "جميع الفواتير": "All Invoices",
    "عروض الأسعار": "Quotations",
    "الحجوزات": "Reservations",
    "إرسال التقرير للمدير": "Send Report to Manager",
    "الكمية": "Quantity",
    "إجراء": "Action",
    "إجراءات": "Actions",
    "اليوم": "Today",
    "هذا الشهر": "This Month",
    "هذه السنة": "This Year",
    "تصدير": "Export",
    "إضافة مصروف": "Add Expense",
    "الملخص": "Summary",
    "الإيرادات": "Revenues",
    "المصروفات": "Expenses",
    "الأرباح والخسائر": "Profit & Loss",
    "القيود اليومية": "Daily Journal",
    "إجمالي المصروفات": "Total Expenses",
    "صافي الربح": "Net Profit",
    "رصيد الصندوق": "Safe Balance",
    "إضافة مصروف جديد": "Add New Expense",
    "رصيد الصندوق الحالي": "Current Safe Balance",
    "المستخدم": "User",
    "مسح السجل": "Clear Log",
    "ابحث في السجل...": "Search in log...",
    "🔍 ابحث في السجل...": "🔍 Search in log...",
    "اضغط \"إتمام البيع\" پشتی تەئکیدێ ل سەر دانا پارەی ب ئامێری": "Press \"Complete Sale\" after confirming payment on the terminal",
    "اضغط \"إتمام البيع\" پشتی تەئکیدکرنێ ژ گەهشتنا حەوالەیێ": "Press \"Complete Sale\" after confirming transfer receipt",
    "scan_btn": "Scan",
    "clear_btn": "Clear Cart",
    "vouchers": "Receipt Vouchers",
    "receipt_voucher": "Receipt Voucher",
    "add_voucher": "Create Voucher",
    "voucher_no": "Voucher No",
    "voucher_date": "Date",
    "received_from": "Received From",
    "voucher_amount": "Amount",
    "voucher_note": "Note",
    "voucher_payment_method": "Payment Method",
    "print_voucher": "Print Voucher",
    "delete_voucher": "Delete Voucher",
    "vouchers_desc": "Create, manage, and print receipt vouchers and incoming payments",
    "وصولات القبض": "Receipt Vouchers",
    "+ إضافة وصل قبض": "+ Add Receipt Voucher",
    "العميل / الجهة": "Client / Entity",
    "لا توجد وصولات قبض بعد": "No receipt vouchers yet",
    "وصل قبض جديد": "New Receipt Voucher",
    "المبلغ المقبوض (د.ع)": "Received Amount (IQD)",
    "إيداع في": "Deposit Into",
    "تأكيد القبض": "Confirm Receipt",
    "+ مرتجع جديد": "+ New Return",
    "+ إضافة دفعة": "+ Add Payment"
  },
  "statusMap": {
    "متوفر": "Available",
    "منخفض": "Low",
    "نفد": "Out of Stock",
    "نشط": "Active",
    "مدير": "Admin",
    "محاسب": "Accountant",
    "كاشير": "Cashier",
    "عملية": "Operation"
  }
};
